### PR TITLE
Rework summary prompt

### PR DESCRIPTION
**Pull request by plaliberte**
I've been through a few iterations on the prompt  but from my experimentation so far I think that using the same summarization prompt in two passes is giving me the best result.  I will experiment a bit more after

### CODE REVIEW

**Comment by tackaberry** [comment]
Ok,  cool.  If I were to fill in the gaps here, I would think the learning here is in "two passes of summarization", but not particularly the same prompt. I would hazard a guess you could continue to improve if you separate the prompts into two passes.  So, I would suggest two things:

1.  Create two different summarization prompts.  This allows us better control to abstract the prompt and give us the ability to tweak the prompts independently.  For the purpose of this PR, dont worry about changing the first or second prompt, just separate as `summarization_step_1` and `summarization_step_2`

2. Secondly, i think you should still do a summarization step1 on single pages.

**Comment by plaliberte** [comment]
Agreed, I'm happy to explore that further.  I initially started down that path which is why I had broken out the run_prompt method on its own but I wasn't getting great results.  I think we can get there with what you are suggesting, but it will take a little bit more work in prompt design to get it to work properly.

**Comment by tackaberry** [comment]
Just rework to support the approach and commit with the exact same prompt and we can take it from there.  I want to test with the 2 prompts.

**Comment by plaliberte** [comment]
@tackaberry I split out the methods to make it easier to experiment with different prompts.

**Pull request merged**
